### ISSUE TITLE
Error in date->time-utc or time-utc->date in windows 

### ISSUE THREAD

**Issue by gus-massa** [cisco/ChezScheme#247] opened 2017-12-22 01:45 UTC
In the test in WIndows, I get this error in [date.ms#L624-L627](https://github.com/cisco/ChezScheme/blob/master/mats/date.ms#L624-L627)

    (let ([t (current-time)])
      (time=?
        (date->time-utc (time-utc->date t -14400))
        (date->time-utc (time-utc->date t 0))))

The error in the summary is something like

    -------- o=0 --------
    > date.mo:Bug in mat conversions/sleep clause 7 at line 624, char 3 of date.ms

For reference, when I run this variation manually I get this results:

    (let ([t (current-time)])
      (list
        (date->time-utc (time-utc->date t -14400))
        (date->time-utc (time-utc->date t))))
    ;==> (#<time-utc 0.897842400> #<time-utc 1513881033.897842400>)

**Comment by burgerrg** [comment] 2017-12-28 17:10
I can't reproduce this problem. Is your TZ environment variable set? If so, unset it and try again.

**Comment by akeep** [comment] 2017-12-28 17:29
I was just looking at this a few minutes ago.  When I changed my time zone to Europe (Berlin), I was able to reproduce the error.  I tried setting the TZ environment variable to 'Europe/Berlin', but that didn't seem to help.

**Comment by gus-massa** [comment] 2017-12-28 17:51
In cygwin I get

    $ echo $TZ
    America/Buenos_Aires

and using `unset TZ` doesn't fix the problem.

In cmd.exe I don't have anything similar to a `TZ` variable, but my timezone is set to "(UTC-03:00) Ciudad de Buenos Aires".

I get similar results `(#<time-utc 0...> #<time-utc 151...>)` running scheme in cmd.exe and in cygwin (with and without TZ)

**Comment by burgerrg** [comment] 2017-12-28 18:43
Thanks, I'm now able to reproduce the behavior on my Windows 10 machine.

**Comment by burgerrg** [comment] 2017-12-29 20:59
The bug is called by the use of difftime in S_mktime, which cannot take a negative time_t value. See https://msdn.microsoft.com/en-us/library/3wbd7281.aspx.

**Comment by burgerrg** [comment] 2017-12-29 21:54
Fixed in commit https://github.com/cisco/ChezScheme/commit/4748dad50c7f0e9b3ba002c27990d4c88c0189fc. I removed the incorrect use of difftime on all platforms and tested against a6le, a6nt, and a6osx.

**Closed** 2017-12-29 21:54 UTC
