### ISSUE TITLE
missing file in csv9.5.tar.gz

### ISSUE THREAD

**Issue by noname007** [cisco/ChezScheme#348] opened 2018-09-13 08:14 UTC
after download source code from https://github.com/cisco/ChezScheme/releases/download/v9.5/csv9.5.tar.gz,

i found no submodule files and when i run `./configure && make` its failed beacause not found file

**Comment by TisonKun** [comment] 2018-09-21 06:19
@noname007 Could you please share the command line output(i.e. error message) here?

I have download csv9.5 from the link you pasted above and can find the submodule files and run `./configure && make` successfully.

**Comment by noname007** [comment] 2018-09-21 13:58
```
$ make
(cd a6osx && make build)
(cd c ; make)
(cd ../zlib; CFLAGS=-m64 ./configure --64)
/bin/sh: ./configure: No such file or directory
make[2]: *** [Makefile:40: ../zlib/configure.log] Error 127
make[1]: *** [Makefile:20: build] Error 2
make: *** [Makefile:19: build] Error 2
````

**Comment by noname007** [comment] 2018-09-21 13:58
```
$ tree zlib
zlib

0 directories, 0 files
```

**Comment by noname007** [comment] 2018-09-21 13:59
```
$ tree stex
stex

0 directories, 0 files
```

**Comment by noname007** [comment] 2018-09-21 14:02
@TisonKun i download anthoer copy and i found that missing file was here and archive packege was lagare 2m than downloaded that day

**Comment by noname007** [comment] 2018-09-21 14:02
![image](https://user-images.githubusercontent.com/8514816/45885823-09d8cc00-bdea-11e8-9c59-50ce069a5acd.png)
![image](https://user-images.githubusercontent.com/8514816/45885836-13623400-bdea-11e8-832a-71dd2d77abeb.png)

**Comment by TisonKun** [comment] 2018-09-21 14:04
OK, I just try to send a mail to you and help, since I think it is an adhoc issue. But it seems be resolved.

Could you close this issue since it isn't reproduced?

**Comment by akeep** [comment] 2018-09-21 14:06
What was the output when you ran configure?



On September 21, 2018 at 9:58:59 AM, soul11201 (notifications@github.com)
wrote:

$ make
(cd a6osx && make build)
(cd c ; make)
(cd ../zlib; CFLAGS=-m64 ./configure --64)
/bin/sh: ./configure: No such file or directory
make[2]: *** [Makefile:40: ../zlib/configure.log] Error 127
make[1]: *** [Makefile:20: build] Error 2
make: *** [Makefile:19: build] Error 2

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cisco/ChezScheme/issues/348#issuecomment-423540294>,
or mute
the thread

**Comment by noname007** [comment] 2018-09-25 06:29
@TisonKun Ok

**Closed** 2018-09-25 06:28 UTC
