### ISSUE TITLE
./configure fails with zip download but not with git clone

### ISSUE THREAD

**Issue by haziz** [cisco/ChezScheme#131] opened 2016-12-06 16:38 UTC
When using the zip file download feature (as opposed to git cloning the project) [the green download button offers an option for a zip download in addition to git cloning via either ssh or https].

When you try to ./configure the unzipped project it responds with an error about rmdir being unable to rm the nanopass directory and then exits. This does not occur with the git cloned project. As a result you cannot configure and build with the zipped "tarball".

Thanks.

**Comment by akeep** [comment] 2016-12-06 17:13
Hey @haziz,

What platform are you on?  I've just tried both the tarball and the zip on my Mac, and both build fine. 

Is it possible that when you unzip the zip file or untar the tar.gz file it is setting read-only permissions on the expanded directories?

From the downloaded tarball:
```
$ tar zxvf ChezScheme-9.4.tar.gz
$ cd ChezScheme-9.4
```
Then we can check the permissions and ownership on the directories that are going to be replaced by the ``rmdir`` and ``curl`` commands:

```
$ ls -laF nanopass zlib stex
nanopass:
total 0
drwxr-x---@  2 akeep  staff   68 May 13  2016 ./
drwxr-x---@ 29 akeep  staff  986 Dec  6 12:05 ../

stex:
total 0
drwxr-x---@  2 akeep  staff   68 May 13  2016 ./
drwxr-x---@ 29 akeep  staff  986 Dec  6 12:05 ../

zlib:
total 0
drwxr-x---@  2 akeep  staff   68 May 13  2016 ./
drwxr-x---@ 29 akeep  staff  986 Dec  6 12:05 ../
```

These permissions allow for writing in both the ``ChezScheme-9.4`` directory and the `` nanopass``, ``stex``, and ``zlib`` directories, and I am the owner of these directories, so my permissions and ownership match up.

Now were are ready to ``configure`` and ``make`` , I've elided some of the output here.

```
$ ./configure
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   140    0   140    0     0    889      0 --:--:-- --:--:-- --:--:--   891
100 3726k    0 3726k    0     0  3837k      0 --:--:-- --:--:-- --:--:-- 6863k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   119    0   119    0     0    722      0 --:--:-- --:--:-- --:--:--   725
100  590k  100  590k    0     0  1790k      0 --:--:-- --:--:-- --:--:-- 19.8M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   119    0   119    0     0    757      0 --:--:-- --:--:-- --:--:--   762
100  206k    0  206k    0     0   583k      0 --:--:-- --:--:-- --:--:--  583k
$ make
(cd a6osx && /Applications/Xcode.app/Contents/Developer/usr/bin/make build)
(cd c ; /Applications/Xcode.app/Contents/Developer/usr/bin/make)
.
.
.
bootfile comparison succeeded
/Applications/Xcode.app/Contents/Developer/usr/bin/make restoreboot
mv -f ../boot/a6osx/sbb ../boot/a6osx/petite.boot
mv -f ../boot/a6osx/scb ../boot/a6osx/scheme.boot
/Applications/Xcode.app/Contents/Developer/usr/bin/make resetbootlinks
touch bootstrap
$
```

We should see the same thing from the zip file (and I did in my test of this), I've again elided some of the output, here of the ``unzip`` command.

```
$ unzip ChezScheme-9.4.zip
Archive:  ChezScheme-9.4.zip
d74078aee4dac3ee3b10bdcf42ecf1b8e2e817f0
   creating: ChezScheme-9.4/
.
.
.
finishing deferred symbolic links:
  ChezScheme-9.4/csug/canned/csug.css -> ../csug.css
$ cd ChezScheme-9.4
$ ls -laF nanopass zlib stex
nanopass:
total 0
drwxr-x---@  2 akeep  staff   68 May 13  2016 ./
drwxr-x---@ 29 akeep  staff  986 May 13  2016 ../

stex:
total 0
drwxr-x---@  2 akeep  staff   68 May 13  2016 ./
drwxr-x---@ 29 akeep  staff  986 May 13  2016 ../

zlib:
total 0
drwxr-x---@  2 akeep  staff   68 May 13  2016 ./
drwxr-x---@ 29 akeep  staff  986 May 13  2016 ../
```

Again the permissions and ownership of the three directories match up and we are ready to ``configure`` and ``make``.  I've again elided some of the output for the sake of brevity.

```
$ ./configure
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   140    0   140    0     0    710      0 --:--:-- --:--:-- --:--:--   714
100 3726k  100 3726k    0     0  4058k      0 --:--:-- --:--:-- --:--:-- 18.1M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   119    0   119    0     0    629      0 --:--:-- --:--:-- --:--:--   632
100  590k  100  590k    0     0  1691k      0 --:--:-- --:--:-- --:--:-- 1691k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   119    0   119    0     0    517      0 --:--:-- --:--:-- --:--:--   517
100  206k  100  206k    0     0   551k      0 --:--:-- --:--:-- --:--:--  551k
$ make
(cd a6osx && /Applications/Xcode.app/Contents/Developer/usr/bin/make build)
(cd c ; /Applications/Xcode.app/Contents/Developer/usr/bin/make)
.
.
.
bootfile comparison succeeded
/Applications/Xcode.app/Contents/Developer/usr/bin/make restoreboot
mv -f ../boot/a6osx/sbb ../boot/a6osx/petite.boot
mv -f ../boot/a6osx/scb ../boot/a6osx/scheme.boot
/Applications/Xcode.app/Contents/Developer/usr/bin/make resetbootlinks
touch bootstrap
$
```

**Comment by akeep** [comment] 2017-06-10 17:36
Since there is no further feedback on this, I'm going to close it, since I cannot reproduce the problem.

**Closed by akeep** 2017-06-10 17:36 UTC

**Comment by haziz** [comment] 2017-06-28 23:40
Actually this still happens. I once again could not install from the "zipped" tarball downloaded from Github but was able when I just git cloned the repository. The system on which this failed is a fresh install of Debian 9 ("Stretch") 64 bit. I did install the X11 and ncurses dev libraries and headers since Debian does not install them by default.

My terminal output:

haziz@stretch:~/src/ChezScheme-master$ ./configure 
rmdir: failed to remove 'nanopass': No such file or directory

**Comment by Nillouise** [comment] 2017-09-20 06:39
I have this problem too.I find it cause by my Debian system didn't install curl command.So at first I run ./configure  it delete the  'nanopass' folder.And second time I run the ./configure,it say  failed to remove 'nanopass': No such file or directory.

I solve this by install curl.
