### ISSUE TITLE
default function arguments in chez?

### ISSUE THREAD

**Issue by durandaltheta** [cisco/ChezScheme#370] opened 2018-12-12 16:02 UTC
I'm coming from Racket where setting a default argument is done:
```
(define (myfunc [a 'default-value]) ...)
```
Which doesn't seem to work in chez:
```
Chez Scheme Version 9.5.1
Copyright 1984-2017 Cisco Systems, Inc.

> (define (myfunc [a 'default-value]) a)
Exception: invalid syntax (define (myfunc (a (...))) a)
Type (debug) to enter the debugger.
> (define (myfunc (a 'default-value)) a)
Exception: invalid syntax (define (myfunc (a (...))) a)
Type (debug) to enter the debugger.
>
```

Is there any way to set a default function argument in chez?

EDIT:
I just discovered [case-lambda](https://www.scheme.com/tspl4/binding.html#./binding:h3), is that the best way to do optional arguments in chezscheme?

**Comment by ovenpasta** [comment] 2018-12-12 23:53
Hi, you could use case-lambda...

https://scheme.com/tspl4/binding.html#./binding:s13

or... use some utility macros...

Example:

```
> (import (thunder-utils))
> (define/optional (add-some x (/optional (y 1) print))
    (let ([sum (+ x y)])
      (if print (printf "~d~n" sum))
      sum))
> (add-some 5)
6
> (add-some 5 2)
7
> (add-some 5 2 #t)
7
7
```

Check the code here:   

https://pizzahack.eu/fossil/thunderchez/artifact/bb8d60127e0fea6f

**Comment by amirouche** [comment] 2019-06-01 22:55
If the problem is solved. Please close the issue :+1:

**Closed** 2021-06-08 23:00 UTC
